openapi: 3.0.0
info:
  title:  Radix
  version: 1.0.0
  description: Radix donation app API docs
paths:
  /auth/verify-wallet:
    post:
      summary: verify wallet address
      tags:
        - authentication
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyWalletRequest"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        400:
          description: errors
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /donations/create:
    parameters:
      - $ref: "#/components/parameters/AuthToken"
    post:
      summary: create a donation
      tags:
        - donation
      operationId: createDonation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDonationRequest"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Donation"
        401:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /donations/update:
    parameters:
      - 



  /user/me:
    parameters:
      - $ref: '#/components/parameters/AuthToken'
    get:
      summary: get user details
      tags:
        - user
      operationId: getUserDetails
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /donations:
    get:
      summary: view all donations
      tags:
        - donation
      operationId: getAllDonations
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Donation"

  /donation/{donationId}:
    parameters:
      - $ref: "#/components/parameters/DonationParam"
    get:
      summary: get a single donation
      tags:
        - donation
      operationId: getSingleDonation
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Donation"
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /donations/me:
    parameters:
      - $ref: "#/components/parameters/AuthToken"
    get:
      summary: get all user donations
      tags:
        - donation
      operationId: getUserDonations
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Donation"

  /donations/donors/:donationId:
    parameters:
      - $ref: "#/components/parameters/DonationParam"
    get:
      summary: get donors
      tags:
        - donation
      operationId: getDonors
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"

  /donations/track:
    parameters:
      - $ref: "#/components/parameters/AuthToken"
    post:
      summary: track donations
      tags:
        - donation
      operationId: track donation attempts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrackDonationRequest"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponse"











components:
  parameters:
    AuthToken:
      name: x-auth-token
      in: header
      schema:
        type: string
      required: true
    DonationParam:
      name: donationId
      in: path
      schema:
        type: string
      required: true
  schemas:
    DefaultResponse:
      title: DefaultResponse
      type: object
      properties:
        message:
          type: string
      required:
        - message

    ErrorResponse:
      title: DefaultResponse
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - message

    ##== REQUESTS ====##
    VerifyWalletRequest:
      type: object
      properties:
        message:
          type: string
        signature:
          type: string
        address:
          type: string

    TrackDonationRequest:
      type: object
      properties:
        transactionHash:
          type: string
        donationId:
          type: string

    CreateDonationRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        target:
          type: number
        raised:
          type: number



  ##----- RESPONSE ------##
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/AuthResponse"

    User:
      type: object
      properties:
        id:
          type: string
        walletAddress:
          type: string

    Transaction:
      type: object
      properties:
        id:
          type: string
        donorAddress:
          type: string
        transactionHash:
          type: string
        donation:
          type: string
          format: uuid
        amount:
          type: number


    Donation:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        wallet:
          type: string
        target:
          type: number
        raised:
          type: number